---
driver:
  name: vagrant
  customize:
    memory: 2048
  network:
    - ["public_network", bridge: 'eth0']

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[rethinkdb::default]
    attributes:
